version: '3'
services:
  traefik:
    image: traefik:latest # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - '80:80' # The HTTP port
      - '8080:8080' # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  chat:
    # build: .
    image: ha-chat
    environment:
      - REDIS_HOST=redis
      - DOMAIN=http://chat.test
    labels:
      - 'traefik.frontend.rule=Host:chat.test'
      - 'traefik.backend=chat'
